/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Energy': '能源',
    ' Energy': ' 能源',
    ' Energy, ': ' 能源, ',
    'Gems': '宝石',
    ' Gems': ' 宝石',
    ' Gems, ': ' 宝石, ',
    'Gold': '黄金',
    ' Gold': ' 黄金',
    ' Gold, ': ' 黄金, ',
    'Ice': '冰',
    ' Ice': ' 冰',
    ' Ice, ': ' 冰, ',
    'Lava': '岩浆',
    ' Lava': ' 岩浆',
    ' Lava, ': ' 岩浆, ',
    'Silicon': '硅',
    ' Silicon': ' 硅',
    ' Silicon, ': ' 硅, ',
    'Silver': '银',
    ' Silver': ' 银',
    ' Silver, ': ' 银, ',
    'Wood': '木头',
    ' Wood': ' 木头',
    ' Wood, ': ' 木头, ',
    ' wood': ' 木头',
    ' wood, ': ' 木头, ',
    'Oil': '石油',
    ' Oil': ' 石油',
    ' Oil, ': ' 石油, ',
    'Plasma': '等离子体',
    ' Plasma': ' 等离子体',
    ' Plasma, ': ' 等离子体, ',
    'Metal': '金属',
    ' Metal': ' 金属',
    ' Metal, ': ' 金属, ',
    'Titanium': ' 钛',
    ' Titanium': ' 钛',
    ' Titanium, ': ' 钛, ',
    'Charcoal': '木炭',
    ' Charcoal': ' 木炭',
    ' Charcoal, ': ' 木炭, ',
    'Space': '太空',
    '	Hard Reset': '硬重置',
    '	Load': '加载',
    ' Company': ' 公司',
    ' Company ': ' 公司',
    'Company ': '公司 ',
    'Company': '公司',
    'Convert ': '转换',
    'Convert': '转换',
    'Converting ': '转换',
    'Costs ': '花费 ',
    'Costs': '花费 ',
    'Big Bertha': '贝尔莎大炮',
    '/Sec': '/秒',
    ' Research': '研究',
    ' Resources': '资源',
    'Sol Center': '索尔中心',
    'Solar Panels': '太阳能板',
    'Solar System': '太阳系',
    'Ice Drill': '冰钻',
    'Igneous Extruder': '火成岩挤出机',
    'Lava Extractor': '熔岩提取器',
    ' Machines': '机器',
    'Magmatic Dynamo': '岩浆发电机',
    'Each Solar Panel produces ': '每个太阳能板生产 ',
    'Each engine produces': '每台发动机生产',
    'Earth Resources': '地球资源',
    'Electron Bath': '电子浴',
    'Empowered Blowtorch': '增压喷灯',
    'Gain ': '获取 ',
    'Get Advanced Drill': '获取 高级钻',
    'Get Annihilator': '获取 歼灭者',
    'Get Asteroid Destroyer': '获取 小行星驱逐舰',
    'Get Atomic Cannon': '获取 原子炮',
    'Get Battery': '获取 电池',
    'Get Battery T': '获取 T电池',
    'Get Big Bertha': '获取 贝尔莎大炮',
    'Get Biomass Infuser': '获取 生物质注入器',
    'Get Blowtorch': '获取 喷灯',
    'Get Caged Star': '获取 笼星',
    'Get Carbyne Drill': '获取 卡宾钻',
    'Get Charcoal Engine': '获取 木炭发动机',
    'Get Chronal Actuator': '获取 定向致动器',
    'Get Club': '获取 俱乐部',
    'Get Collector': '获取 收集器',
    'Get Crucible': '获取 坩埚',
    'Get Cubic Teleposer': '获取 集成电路电视',
    'Get Dead Werewolf Finder': '获取 死亡狼人探测器',
    'Get Death Star Jr': '获取 死星JR',
    'Get Desert Destroyer': '获取 沙漠驱逐舰',
    'Get Diamond Accretion Chamber': '获取 钻石吸积室',
    'Get Diamond Drill': '获取 金刚石钻',
    'Get Drone': '获取 无人机',
    'Get Electrolytic Cell': '获取 电解池',
    'Get Electron Bath': '获取 电子浴',
    'Get Explorer': '获取 探测器',
    'Get Extractor': '获取 提取器',
    'Get Forest Fryer': '获取 森林炸锅',
    'Get Fossilator': '获取 化石器',
    'Get Freezer': '获取 冰箱',
    'Get Furnace': '获取 熔炉',
    'Get Fusion Reactor': '获取 聚变反应堆',
    'Get Gas Giant Skimmer': '获取 巨型气体分离器',
    'Get Gem Miner': '获取 宝石矿工',
    'Get Giga Drill': '获取 千兆钻',
    'Get Grinder': '获取 磨床',
    'Get Heavy Drill': '获取 重型钻',
    'Get Hindenburg Excavation': '获取 兴登堡挖掘',
    'Get Hydrothermal Vent': '获取 水热排气',
    'Get Ice Drill': '获取 冰钻',
    'Get Ice Pickaxe': '获取 冰镐',
    'Get Igneous Extruder': '获取 火成岩挤出机',
    'Get Industrial Kiln': '获取 工业窑炉',
    'Get Interplanetary Laser': '获取 星际激光',
    'Get Interstellar Cow': '获取 星际牛',
    'Get Jupitonian Condensator': '获取 木星冷凝器',
    'Get Laser Cutter': '获取 激光切割机',
    'Get Low-Gravity Drill': '获取 ',
    'Get Lunarite Drill': '获取 月岩钻',
    'Get Magmatic Dynamo': '获取 岩浆发电机',
    'Get Magnet': '获取 磁铁',
    'Get Mass Deforester': '获取 大规模毁林者',
    'Get Meteorite Printer': '获取 陨石打印机',
    'Get Meteorite Web': '获取 陨石网',
    'Get meteorites the old-fashioned way: demolishing uninhabited exoplanets by firing high-energy particle beams at them, then collect the debris': '用老式的方法获取陨石：向其发射高能粒子束以摧毁无人系外行星，然后收集碎片',
    'Get Methane Power Station': '获取 甲烷发电站',
    'Get Microverse Pollutor': '获取 微宇宙探测器',
    'Get Miner': '获取 矿工',
    'Get Moon Cloner': '获取 月球克隆者',
    'Get Moon Quarry': '获取 月球采石场',
    'Get Moon Worker': '获取 月球工人',
    'Get Morphic Compressor': '获取 形态压缩机',
    'Get Mr Freeze': '获取 急冻人',
    'Get Multiverse Drill': '获取 多元宇宙钻',
    'Get Nebulous Synthesizer': '获取 星云合成器',
    'Get Nuclear Power Station': '获取 核电站',
    'Get Offshore Rig': '获取 海上钻机',
    'Get Oil Field': '获取 油田',
    'Get Overexchange Condenser': '获取 过度交换冷凝器',
    'Get Penta-Drill': '获取 五角钻',
    'Get Philosopher\'s Stone': '获取 魔法石',
    'Get Planet Smasher': '获取 行星粉碎机',
    'Get Planetary Excavator': '获取 行星挖掘机',
    'Get Planetary Nuclear Plant': '获取 行星核工厂',
    'Get Plasmatic Pit': '获取 等离子坑',
    'Get PSU': '获取 电源模块',
    'Get PSU T': '获取 T电源模块',
    'Get Pump': '获取 水泵',
    'Get Pumpjack': '获取 抽油机',
    'Get Quantum Drill': '获取 量子钻',
    'Get Rocket Droid': '获取 火箭机器人',
    'Get Russian Forest': '获取 俄罗斯森林',
    'Get Scout Ship': '获取 侦察船',
    'Get Seaside Scorcher': '获取 海边烤炉',
    'Get Solar Panel': '获取 太阳能板',
    'Get Space Cow': '获取 太空牛',
    'Get Star Harvester': '获取 星际收割机',
    'Get Suction Excavator': '获取 吸挖机',
    'Get Super-Heater': '获取 超级加热器',
    'Get T.A.R.D.I.S': '获取 塔迪斯',
    'Get Tanker': '获取 油船',
    'Get Titan-Drill': '获取 泰坦钻',
    'Get Uranium Enricher': '获取 铀浓缩器',
    'Get Vacuum Cleaner': '获取 真空吸尘器',
    'Get Volcanic Veluptuator': '获取 火山起伏器',
    'Get Woodburner': '获取 烧炭工',
    'Get Woodcutter': '获取 伐木工',
    'Get Yellowcake Recycler': '获取 黄饼回收器',
    'Giga Drill': '千兆钻',
    'Giga Drills extract Metal at colossal speeds': '千兆钻以极高的速度提取金属',
    'Grinder': '磨床',
    'Explorer': '探测器',
    'Exploration': '勘探',
    'Helium': '氦气',
    ' Helium': ' 氦气',
    ' Helium, ': ' 氦气, ',
    'Lunarite': '月岩',
    ' Lunarite': ' 月岩',
    ' Lunarite, ': ' 月岩, ',
    'Hydrogen': '氢气',
    ' Hydrogen': ' 氢气',
    ' Hydrogen, ': ' 氢气, ',
    'Meteorite': '陨石',
    ' Meteorite': ' 陨石',
    ' Meteorite, ': ' 陨石, ',
    'Methane': '甲烷',
    ' Methane': ' 甲烷',
    ' Methane, ': ' 甲烷, ',
    'Uranium': '铀',
    ' Uranium': ' 铀',
    ' Uranium, ': ' 铀, ',
    'Off': '关闭',
    ' Off': ' 关闭',
    ' More..': ' 更多...',
    ' Help / FAQ': ' 帮助 / FAQ',
    'Build': '建造',
    ' Gems per second': ' 宝石 每秒',
    ' Wood per second': ' 木头 每秒',
    ' wood per second': ' 木头 每秒',
    ' Metal per second': ' 金属 每秒',
    ' Charcoal per second': ' 木炭 每秒',
    ' Energy per second': ' 能源 每秒',
    'Offshore Rig': '海上钻机',
    'Penta-Drill': '五角钻',
    'Pluto': '冥王星',
    'Explore Moon': '探索月亮',
    'Explore Asteroid Belt': '探索小行星带',
    'Explore Jupiter': '探索木星',
    'Explore Kuiper Belt': '探索柯伊伯带',
    'Explore Mars': '探索火星',
    'Explore Pluto': '探索冥王星',
    'Explore Saturn': '探索土星',
    'Explore Sol Center': '探索索尔中心',
    'Explore The Wonder Station': '探索奇迹站',
    'Explore Venus': '探索金星',
    'full': '满',
    'Gem Miner': '宝石矿工',
    'Helium Tanker': '氦气运输船',
    'Not Built': '未建造',
    'Rocket': '火箭',
    'Saturn': '土星',
    'Scout Ship': '侦察船',
    'Neptune': '海王星',
    'Moon Quarry': '月球采石场',
    'Ocean Freezer': '海洋冷冻柜',
    'Oil Field': '油田',
    'Oil Fields are large open spaces, usually found in deserts where vast oil wells can be found under the ground': '油田是大型的露天场所，通常在沙漠中发现，在地下可以找到巨大的油井',
    'Offshore Rigs are megastructures floating in the oceans, extracting Oil from under the sea-beds': '海上钻机是漂浮在海洋中的巨型结构，从海床下开采石油',
    'Rocket Fuel': '火箭燃料',
    'Rocket fuel is created in chemical plants and is used to allow rockets to launch off into space and to travel to other planets and star systems': '火箭燃料是在化工厂中产生的，用于使火箭发射到太空并传播到其他行星和恒星系',
    'Small Pump': '小型泵',
    'Technologies': '技术',
    'The Moon': '月球',
    'The Moon is our largest satellite, revolving around the Earth once every 27 days. It contains a large quantity of Lunarite, left over from when it separated from the Earth billions of years ago. It is much stronger than regular metal and used to build more advanced machines': '月球是我们最大的卫星，每27天绕地球旋转一次。 它包含大量的月岩，是数十亿年前它与地球分离时留下的。 它比普通金属坚固得多，用于制造更先进的机器',
    'The Sol Scientific Center': '索尔科学中心',
    'The Super-Heater throws electricity at Hydrogen to turn it into a plasmatic substance': '这个超级加热器把电投向氢，把氢变成一种可塑物质',
    'Death Star Jr': '死星Jr',
    'David Guetta\'s Club': '大卫·库塔的俱乐部',
    'Cubic Teleposer': '集成电路电视',
    'Desert Destroyer': '沙漠驱逐舰',
    'Destroy Advanced Drill': '摧毁 高级钻',
    'Destroy Atomic Cannon': '摧毁 原子炮',
    'Destroy Beach Annihilator': '摧毁 海滩歼灭者',
    'Destroy Big Bertha': '摧毁 贝尔莎大炮',
    'Destroy Biomass Infuser': '摧毁 生物质注入器',
    'Destroy Caged Star': '摧毁 笼星',
    'Destroy Carbyne Drill': '摧毁 卡宾钻',
    'Destroy Charcoal Engine': '摧毁 木炭发动机',
    'Destroy Chemical Plant': '摧毁 化工厂',
    'Destroy Chronal Actuator': '摧毁 定向致动器',
    'Destroy Club': '摧毁 俱乐部',
    'Destroy Collector': '摧毁 收集者',
    'Destroy Cubic Teleposer': '摧毁 集成电路电视',
    'Destroy Dead Werewolf Finder': '摧毁 死亡狼人探测器',
    'Destroy Death Star Jr': '摧毁 死星Jr',
    'Destroy Desert Destroyer': '摧毁 沙漠驱逐舰',
    'Destroy Destroyer': '摧毁 驱逐舰',
    'Destroy Diamond Accretion Chamber': '摧毁 钻石吸积室',
    'Destroy Diamond Drill': '摧毁 金刚石钻',
    'Destroy Droid': '摧毁 机器人',
    'Destroy Electrolytic Cell': '摧毁 电解池',
    'Destroy Electron Bath': '摧毁 电子浴',
    'Destroy Empowered Blowtorch': '摧毁 增压喷灯',
    'Destroy Explorer': '摧毁 探测器',
    'Destroy Forest Fryer': '摧毁 森林炸锅',
    'Destroy Fossilator': '摧毁 化石器',
    'Destroy Furnace': '摧毁 熔炉',
    'Destroy Fusion Reactor': '摧毁 聚变反应堆',
    'Destroy Gas Giant Skimmer': '摧毁 巨型气体分离器',
    'Destroy Gaseous Magnet': '摧毁 气态磁铁',
    'Destroy Gem Miner': '摧毁 宝石矿工',
    'Destroy Giga Drill': '摧毁 千兆钻',
    'Destroy Grinder': '摧毁 磨床',
    'Destroy Heat Resistant Crucible': '摧毁 耐热坩埚',
    'Destroy Heavy Drill': '摧毁 重型钻',
    'Destroy Helium Drone': '摧毁 氦无人机',
    'Destroy Helium Tanker': '摧毁 氦气运输船',
    'Destroy Hindenburg Excavation': '摧毁 兴登堡发掘',
    'Destroy Hydrazine Catalyst': '摧毁 肼催化剂',
    'Destroy Hydrothermal Vent': '摧毁 水热排气',
    'Destroy Ice Drill': '摧毁 冰钻',
    'Destroy Ice Pickaxe': '摧毁 冰镐',
    'Destroy Igneous Extruder': '摧毁 火成岩挤出机',
    'Destroy Industrial Kiln': '摧毁 工业窑炉',
    'Destroy Interstellar Cow': '摧毁 星际牛',
    'Destroy Jupitonian Condensator': '摧毁 木星冷凝器',
    'Destroy Laser Cutter': '摧毁 激光切割机',
    'Destroy Lava Extractor': '摧毁 熔岩提取器',
    'Destroy Low-Gravity Drill': '摧毁 低重力钻',
    'Destroy Lunarite Drill': '摧毁 月岩钻',
    'Destroy Magmatic Dynamo': '摧毁 岩浆发电机',
    'Destroy Mass Deforester': '摧毁 大规模毁林者',
    'Destroy Meteorite Printer': '摧毁 陨石打印机',
    'Destroy Meteorite Web': '摧毁 陨石网',
    'Destroy Methane Station': '摧毁 甲烷站',
    'Destroy Microverse Pollutor': '摧毁 微宇宙探测器',
    'Destroy Miner': '摧毁 矿工',
    'Destroy Moon Cloner': '摧毁 月球克隆者',
    'Destroy Moon Quarry': '摧毁 月球采石场',
    'Destroy Morphic Compressor': '摧毁 形态压缩机',
    'Destroy Mr Freeze': '摧毁 急冻人',
    'Destroy Multiverse Drill': '摧毁 多元宇宙钻',
    'Destroy Nebulous Synthesizer': '摧毁 星云合成器',
    'Destroy Nuclear Station': '摧毁 核电站',
    'Destroy Ocean Freezer': '摧毁 海洋冰柜',
    'Destroy Offshore Rig': '摧毁 海上钻机',
    'Destroy Oil Field': '摧毁 油田',
    'Destroy Overexchange Condenser': '摧毁 过度交换冷凝器',
    'Destroy Oxidisation Chamber': '摧毁 氧化室',
    'Destroy Penta-Drill': '摧毁 五角钻',
    'Destroy Philosopher\'s Stone': '摧毁 魔法石',
    'Destroy Planet Smasher': '摧毁 行星粉碎机',
    'Destroy Planetary Excavator': '摧毁 行星挖掘机',
    'Destroy Planetary Nuclear Plant': '摧毁 行星核工厂',
    'Destroy Plasmatic Pit': '摧毁 等离子坑',
    'Destroy Pumpjack': '摧毁 抽油机',
    'Destroy Quantum Drill': '摧毁 量子钻',
    'Destroy Russian Forest': '摧毁 俄罗斯森林',
    'Destroy Scorcher': '摧毁 海边烤炉',
    'Destroy Scout': '摧毁 侦查兵',
    'Destroy Small Pump': '摧毁 小型泵',
    'Destroy Solar Panel': '摧毁 太阳能电池板',
    'Destroy Space Cow': '摧毁 太空牛',
    'Destroy Space Laser': '摧毁 太空激光',
    'Destroy Star Harvester': '摧毁 星际收割机',
    'Destroy Suction Excavator': '摧毁 吸挖机',
    'Destroy Super-Heater': '摧毁 超级加热器',
    'Destroy T.A.R.D.I.S': '摧毁 塔迪斯',
    'Destroy Titan-Drill': '摧毁 泰坦钻',
    'Destroy Uranium Enricher': '摧毁 铀浓缩器',
    'Destroy Vacuum Cleaner': '摧毁 真空吸尘器',
    'Destroy Volcanic Veluptuator': '摧毁 火山起伏器',
    'Destroy Woodburner': '摧毁 烧炭工',
    'Destroy Woodcutter': '摧毁 伐木工',
    'Destroy Yellowcake Recycler': '摧毁 黄饼回收器',
    'Diamond Accretion Chamber': '钻石吸积室',
    'Diamond Encrusted Drill': '镶钻钻',
    'Space Cow Plantation': '太空牛种植园',
    'Space Rocket': '宇宙火箭',
    'Space Scientific Satellite Station': '空间科学卫星站',
    'Speeds up time through quantum physics in order to produce even more Gold': '通过量子物理学加快时间以生产更多金',
    'Somehow, it works': '不知何故，它起作用了',
    'Star Harvester': '星际收割机',
    'Stargate': '星际之门',
    'Super-Heater': '超级加热器',
    'Technological Wonder': '技术奇迹',
    'Science Production': '科学生产',
    'Donate Resources': '捐赠资源',
    'Dormant': '休眠',
    'Drill of Titans': '泰坦钻',
    'Each engine produces ': '每个发动机生产 ',
    'Each one produces ': '每一个生产 ',
    'Mercury': '水星',
    'Mercury is a lifeless rock with little to no value. It is not worth exploring on the ground as there are no valuable materials present': '水星是一块没有生命的石头，几乎没有价值。因为没有珍贵的资料，所以不值得在地面上进行探索',
    'Meteorite Printer': '陨石打印机',
    'Energetic Wonder': '能量奇迹',
    'Energy Deficit!': '能源短缺！',
    'Electrolytic Cell': '电解池',
    'Fire Moon Worker': '火月工人',
    'Forest Fryer': '森林炸锅',
    'Forests? What forests?': '森林?什么森林?',
    'Fossilator': '化石器',
    'Gas Giant Skimmer': '巨型气体分离器',
    'Ice Pickaxe': '冰镐',
    'Join our Discord!': '加入我们的 Discord!',
    'Jupiter': '木星',
    'Mars': '火星',
    'Mars is the second closest planet to Earth and is covered in red iron oxide, also called rust. You can find Titanium on the surface, but it is more common inside the crust. Titanium will allow for Methane power plants and Silicon production': '火星是离地球第二近的行星，覆盖着红色的氧化铁，也叫铁锈。你可以在表面找到钛，但在地壳内部更常见。钛将用于甲烷发电厂和硅的生产',
    'Metal is one of the primary resources. It is used for many things, including storage upgrades, machinery and most things in space': '金属是主要的资源之一。它被用于很多方面，包括存储升级、机器和太空中的大多数东西',
    'Lunarite Drill': '月岩钻',
    'Mass Deforester': '大规模毁林者',
    'Advanced Drill': '高级钻',
    'Activate Wonder': '激活奇迹',
    'Asteroid Belt': '小行星带',
    'Atomic Cannon': '原子炮',
    'Batteries': '电池',
    'Biomass Infuser': '生物质注入器',
    'Beach Annihilator': '海滩歼灭者',
    'Laser Cutter': '激光切割机',
    'The Rocket Wonder': '火箭奇迹',
    'The Precious Wonder': '珍贵奇迹',
    ' Ice and ': ' 冰 和 ',
    ' Charcoal and ': ' 木炭 和 ',
    ' Gold and ': ' 黄金 和 ',
    ' Silver and ': ' 银 和 ',
    'Upgrade Storage': '升级库存',
    ' Solar System': ' 太阳系',
    ' Sol Center': ' 索尔中心',
    'Turn Rocket Fuel ': '打开火箭燃料',
    'Upgrade your Charcoal storage size to ': '将您的 木炭 存储空间升级到 ',
    'Upgrade your gem storage size to ': '将您的 宝石 存储空间升级到 ',
    'Upgrade your Gold storage size to ': '将您的 黄金 存储空间升级到 ',
    'Upgrade your Helium storage size to ': '将您的 氦气 存储空间升级到 ',
    'Upgrade your Hydrogen storage size to ': '将您的 氢气 存储空间升级到 ',
    'Upgrade your Ice storage size to ': '将您的 冰 存储空间升级到 ',
    'Upgrade your Lava storage size to ': '将您的 岩浆 存储空间升级到 ',
    'Upgrade your Lunarite storage size to ': '将您的 月岩 存储空间升级到 ',
    'Upgrade your Meteorite storage size to ': '将您的 陨石 存储空间升级到 ',
    'Upgrade your Metal storage size to ': '将您的 金属 存储空间升级到 ',
    'Upgrade your methane storage size to ': '将您的 甲烷 存储空间升级到 ',
    'Upgrade your Oil storage size to ': '将您的 石油 存储空间升级到 ',
    'Upgrade your Silicon storage size to ': '将您的 硅 存储空间升级到 ',
    'Upgrade your silver storage size to ': '将您的 银 存储空间升级到 ',
    'Upgrade your Titanium storage size to ': '将您的 钛 存储空间升级到 ',
    'Upgrade your Uranium storage size to ': '将您的 铀 存储空间升级到 ',
    'Upgrade your wood storage size to ': '将您的 木头 存储空间升级到 ',
    'Uranium Enricher': '铀浓缩器',
    '	Costs': ' 花费',
    'Vacuum Cleaner': '真空吸尘器',
    'Woodburner': '烧炭工',
    'Woodcutter': '伐木工',
    'Antimatter Wonder': '反物质奇迹',
    'Build Rocket': '建造火箭',
    'Caged Star': '笼星',
    'Carbyne Drill': '卡宾钻',
    'Charcoal Engine': '木炭发动机',
    'Chemical Plant': '化工厂',
    'Chemical plants are used to make rocket fuel automatically': '化工厂用于自动制造火箭燃料',
    'Charcoal is a secondary tier resource and is used by Engines to produce power for your company. 1 Charcoal is created by burning ': '木炭是次要资源，为发动机提供动力用来为您的公司发电。 生产 1木炭 需要燃烧',
    'Turn Charcoal Production ': '切换 木炭生产 ',
    'Turn Electron Bath ': '切换 电子浴 ',
    'Turn Electron Meteorite ': '切换 陨石生产 ',
    'University Laboratory': '大学实验室',
    'Unlock Plasma Research': '解锁等离子研究',
    'Unlock EMC Machine Research': '解锁EMC机器研究',
    'Uses': '消耗',
    'Uses ': '消耗 ',
    'Volcanic Veluptuator': '火山起伏器',
    'Wonder Station': '奇迹站',
    'Yellowcake Recycler': '黄饼回收器',
    'Wonder Station - Floor': '奇迹站 - 层',
    'Research': '研究',
    'Remaining energy': '剩余能量',
    'Remaining plasma': '剩余等离子体',
    'Rocket Droid': '火箭机器人',
    'Rocket Wonder': '火箭奇迹',
    'Russian Forest': '俄罗斯森林',
    'Seaside Scorcher': '海边烤炉',
    'Storage Upgrade': '存储升级',
    'Quantum Drill': '量子钻',
    'Pumpjack': '抽油机',
    'Produces ': '生产 ',
    'Space Explorer': '宇宙探索',
    'Suction Excavator': '吸挖机',
    'Wood is one of the primary resources. It is used more often in early game for tools and buildings': '木材是主要资源之一。 在早期游戏中经常用于工具和建筑物',
    'Oil is pumped up from the ground and is used to build Tier 2 resource gatherers': '石油从地下开采出来，用于建造第二层资源采集者',
    'Outer Planetary Resources': '外行星资源',
    'Overexchange Condenser': '过度交换冷凝器',
    'Oxidisation Chamber': '氧化室',
    'Philosopher\'s Stone': '魔法石',
    'Helium Drone': '氦气无人机',
    'High School Science': '高中科学',
    'Hindenburg Excavation': '兴登堡挖掘',
    'Time remaining until ': '剩余时间,直到',
    ' storage': '存储',
    ' (Max. ': ' (上限 ',
    'Build an axe for your woodcutter': '为你的伐木工造一把斧头',
    'Build a small pump to extract Oil from the ground': '建一个小泵从地下抽油',
    'Build a small laboratory of your very own to start producing science': '建立一个你自己的小实验室，开始生产科学',
    'Build a shovel for your woodburner': '为你的烧炭人做一把铲子',
    'Build a pickaxe for your miner': '为你的矿工造一把矿镐',
    'Build a more effective laboratory to continue your quest into the realm of science at a significantly faster speed': '建立一个更有效的实验室，继续以更快的速度探索科学领域',
    'Build an even better version of the old laboratory to further your exploration of the realm of science': '在老实验室的基础上再建一个更好的版本，以促进你对科学领域的探索',
    'Build an improved pickaxe to mine Gems': '建造一个改良的挖掘宝石的镐子',
    'Build Chemical Plant': '建造 化工厂',
    'Build Dyson Section': '建造 戴森区',
    'Build Hydrazine Catalyst': '建造 肼催化剂',
    'Build Laboratory T': '建造 实验室 T',
    'Build Oxidisation Chamber': '建造 氧化室',
    'Energy is created by power sources such as steam engines, solar power and advances even to fusion power and nuclear energy. The maximum you can hold to start with is 100,000 Energy, but batteries are unlockable which can increase this': '能源是由蒸汽机、太阳能等能源产生的，甚至在核聚变和核能方面也有进步。一开始你最多可以储存100,000的能源，但是电池是可开启的，这就会增加能源',
    'Cost (Energy': '消耗 (能源',
    'Burns Charcoal to produce a steady source of Energy': '燃烧木炭产生稳定的能源来源',
    'Toggle All Energy Production + Consumption': '切换所有能源生产+消耗',
    ' Energy and uses 1 Charcoal per second': '能源和消耗 1木炭 每秒',
    'Gains Energy slowly from the sun without using any resources': '在不使用任何资源的情况下缓慢地从太阳获得能源',
    'Gaseous Magnet': '气态磁铁',
    ' Wonders': ' 奇迹',
    'Earth': '地球',
    'Earth Machines': '地球机器',
    'Energy Machines': '能源机器',
    'Dyson Segments': '戴森碎片',
    'Fat Free!': '不含脂肪！',
    'Furnace': '熔炉',
    'Fusion Reactor': '聚变反应堆',
    'Miner': '矿工',
    'Moon Cloner': '月球克隆者',
    'Multiverse Drill': '多元宇宙钻',
    'Outer Planets': '外行星',
    'Planet Smasher': '行星粉碎机',
    'Furnaces use electric heaters to produce heat to turn Wood into Charcoal. Because of the increased heat, the process is more efficient': '炉子使用电加热器产生热量，把木头变成木炭。因为增加了热量，这个过程更有效率',
    'Max': '最大',
    'Material': '材料',
    'Machine Name': '机器名称',
    'Manual Saving': '手动保存',
    'Meteorite Web': '陨石网',
    'Meteorite Wonder': '陨石奇迹',
    'Stats': '统计',
    'Sucks more than anything!': '吮吸比什么都重要！',
    'That\'s no moon! That\'s a Space Station! This cuts through asteroids to expose all of the Gold in the centers': '那不是月亮！ 那是空间站！ 这会切穿小行星以暴露中心的所有黄金',
    'Sucks in methane and cleans the planet at the same time!': '吸入甲烷并同时清洁地球！',
    'Rebuild Stargate': '重建星际之门',
    'Rebuild Stargate Wonder': '重建星际之门奇迹',
    'Rebuild Communication Wonder': '重建通讯奇迹',
    'Rebuild Antimatter Wonder': '重建反物质奇迹',
    'PSUs increase your plasma storage by 50,000 per PSU built': '每建造一个电源模块，你的等离子体存储将增加50000',
    'Laser Cutters slice trees (and fingers) more quickly than axes and produce a lot more wood': '激光切割机切割树木(和手指)的速度比斧子更快，产生更多的木材',
    'Kuiper Belt': '柯伊伯带',
    'Achievements': '成就',
    'Advanced Drills mine gem at mass. Because of the toughness of the drill needed it is slower than the heavy drill': '高级钻头大量开采宝石。由于所需要的钻头的韧性，它比重型钻头慢',
    'Auto Emc': '自动 Emc',
    'Base': '基础',
    'Auto-Save Duration': '自动保存时间',
    'Collapse Inner Solar System': '内太阳系坍缩',
    'Collapse Outer Solar System': '外太阳系坍缩',
    'Comms Wonder': '通讯奇迹',
    'Donating': '捐赠',
    'Export Save': '导出存档',
    'Heavy Drill': '重型钻',
    'Heavy Drills mine Metal at mass': '重型钻机大量开采金属',
    'Helium is the second most common element on gas giants such as Jupiter and Saturn': '氦是木星和土星等气态巨行星上第二常见的元素',
    'Home Science Kit': '家庭科学工具箱',
    'Import Save': '导入存档',
    'Import/Export': '导入/导出',
    'Saving': '保存',
    'Sol Scientific Center': '索尔科学中心',
    'The Antimatter Wonder': '反物质奇迹',
    'Themes': '主题',
    'Links': '链接',
    'Hard to handle and only found in volcanoes, Lava is one of the hardest resources to get': '熔岩很难处理，而且只存在于火山中，是最难获得的资源之一',
    'Heat Resistant Crucible': '耐热坩埚',
    'Graphics Options': '图形选项',
    'Screen Notifications': '屏幕通知',
    'Scientific Observatory': '科学观测台',
    'Short Name': '短名称',
    'Short Name (': '短名称 (',
    'Sidebar Height Compression (Not fully implemented)': '侧边栏高度压缩(未完全实现)',
    'Solar': '太阳',
    'Spacelab': '空间实验室',
    'Text Decoration': '文字装饰',
    'Notation': '符号',
    'You can enable settings to change the interface here': '您可以在此处启用设置以更改界面',
    'You can use a modified crucible to pick up lava and to store it for later use': '您可以使用改良的坩埚来拾取熔岩并将其存储以备后用',
    'You currently have ': '您目前有 ',
    'You shoot me down, but I won\'t fall. I am Titanium': '把射死了我，但我不会倒下。我是钛',
    'Copy and paste this onto a file somewhere so that you can import it into the game at a later date': '然后把它粘贴到某个文件上，这样你就可以在以后的游戏中导入它',
    'Copy Text Below To Clipboard': '将下面的文本复制到剪贴板',
    'Create an observatory to gaze upon the stars and acquire knowledge from them': '创建一个天文台来观察星星并从中获得知识',
    'Creating Meteorite is only possible from purer forms of energy than those created with earth technology. Therefore, Plasma is necessary to make the strong resource': '创造陨石只可能从更纯粹的形式的能源比那些与地球技术创造。因此，等离子体是制造强资源所必需的',
    'Creates Wood using old, useless materials found everywhere on Earth by crushing them and packing what remains as densely as possible until it can be used as Wood again': '利用地球上随处可见的旧的、无用的材料来制造木材，把它们压碎，然后把剩下的东西尽可能地打包，直到可以再次用作木材',
    'Cuts through asteroids to find silver deposits in their cores': '穿过小行星，在它们的核心找到银矿',
    'Current amount / Storage': '当前 数量/存储',
    'Dead Werewolf Finder': '死亡狼人探测器',
    'Hydrazine Catalyst': '肼催化剂',
    'Hide Completed Tabs': '隐藏已完成的选项卡',
    'I didn\'t like the intrusiveness of ads on this game and felt that getting people to pay for an in-game boost wouldn\'t bode well in the community as it makes the game feel like a freemium or pay-to-win game': '我不喜欢这款游戏中广告的干扰性，我觉得让人们为游戏中的刺激付费在社区中并不是个好兆头，因为这让游戏感觉像是一款免费增值或付费获胜的游戏',
    'I have a ': '我有一个',
    'Name': '名称',
    '	Save': '保存',
    '	Ring': '环',
    'Hidden': '隐藏',
    'Launch Rocket': '运行火箭',
    'Mr Freeze': '急冻人',
    'Native Moon Worker': '本地月球工人',
    'Paper': '纸',
    'Patreon Page': 'Patreon 页面',
    'PayPal Link': 'PayPal 链接',
    'Planetary Excavator': '行星挖掘机',
    'Getting Started': '入门',
    'Gain Buttons': '增益按钮',
    'Gain Buttons Hidden': '隐藏增益按钮',
    'First Steps': '第一步',
    'Darkly': '黑暗',
    'Cyborg': '半机械人',
    'Construction': '构造',
    'Changelog': '更新日志',
    'Cerulean': '蔚蓝色',
    '		Costs': '花费',
    ' rocket fuel': ' 火箭燃料',
    'The Wonder Station': '奇迹站',
    'The Portal Room': '传送门房间',
    'The Meteorite Wonder': '陨石奇迹',
    'The next section costs': '下一部分花费',
    'Hydrothermal Vent': '水热排气',
    'Industrial Kiln': '工业窑炉',
    'Inner Planet Machines': '内行星机器',
    'More': '更多',
    'Source Code': '源代码',
    'Simplex': '单面',
    'Rounded': '四舍五入',
    'Red Costs: Bold': '红色成本：粗体',
    'Readable': '可读',
    'Precious Wonder': '珍贵奇迹',
    'Output/sec': '输出/秒',
    'Produced: XX/sec': '产生：XX /秒',
    'Nebulous Synthesizer': '星云合成器',
    'Morphic Compressor': '形态压缩机',
    'Microverse Pollutor': '微宇宙探测器',
    'Methane Power Stations': '甲烷发电站',
    'Low-Gravity Drill': '低重力钻',
    'Input/sec': '输入/秒',
    'Inner Planets': '内行星',
    'You can also use this to create multiple \'savefiles\' of the game by storing multiple instances separately': '您还可以通过分别存储多个实例来使用它来创建游戏的多个“存档文件”',
    'When will the game be updated next?': '接下来何时更新游戏？',
    'Warning: This is non-reversible! Be cautious. There is a confirmation to delete your save': '警告：这是不可逆的！ 要小心。 确认删除您的保存',
    'Warning: your stats will not have been added if they were implemented after you achieved them': '警告：如果您在完成统计后实施了统计信息，则不会添加这些统计信息',
    'With advanced technology, you are now able to turn Earth\'s water into high-quality Ice, previously only found on Pluto': '借助先进的技术，您现在可以将地球上的水转化为以前只能在冥王星上找到的优质冰块',
    'Unlock Dyson Sphere Research': '解锁戴森球体研究',
    'Uranus': '天王星',
    'Used: XX/sec': '已用: XX/秒',
    'Uses fission to create large amounts of power': '利用裂变产生大量能量',
    'The Plaza': '广场酒店',
    'The magnet attracts the Hydrogen to it to increase the amount collected per second': '磁铁将氢吸引到其上，以增加每秒收集的量',
    'The largest planet in the solar system, one of four gas giants': '太阳系中最大的行星，四大天然气巨头之一',
    'The Ice Pickaxe is the simplest way of mining frozen water, and although it is the cheapest, it is the slowest': '冰镐是最简单的开采冷冻水的方法，虽然最便宜，但最慢',
    'The Ice Drill is more effective than the Pickaxe and gains much more Ice every second. However, it does use electricity': '冰钻比镐更有效，并且每秒可以获得更多的冰。 但是，它会消耗电',
    'The Helium Drone scouts out the area on Saturn and picks out spots high in Helium which are then mined slowly by it': '氦无人机侦察土星上的区域，并找出高氦点，然后慢慢地开采',
    'The great Russian forests span thousands of miles. More than enough for at least your lifetime. Let the younger generation deal with running out': '俄罗斯的大森林绵延数千英里。至少对你的一生来说是绰绰有余的。让年轻一代自己去解决',
    'The format used is •,••,•••,I,II,III,X,XX,XXX,XXXX,XXXXX,XXXXXX. It is based on the military army hierarchy found on wikipedia at ': '使用的格式是•、•、••、、I、II、III、X、XX、XXX、XXX、XXXX、XXXXX、XXXXX、XXXXXX。它基于维基百科上的军队等级制度',
    'Game Page': '游戏页',
    'Help, I\'m stuck!': '救命，我被卡住了！',
    'Hire explorers to search for Titanium on the surface, uncovered by winds on Mars': '雇佣探险者在火星表面寻找被火星风发现的钛',
    'How does the military level work?': '军事等级是如何运作的?',
    'I found a bug! What should I do?': '我发现了一个错误!我该怎么办?',
    'I have a suggestion for the game': '我对这个游戏有一个建议',
    'I want to help. How do I do that?': '我想帮忙。我该怎么做呢?',
    'If you go to my ': '如果你去我的',
    'Inner Planetary Resources': '内行星资源',
    'Interplanetary Laser': '星际激光',
    'Interstellar Cow': '星际牛',
    'Jupitonian Condensator': '木星冷凝器',
    'Mines through asteroids to find Gold. It is much more effective than the simple droid': '在小行星上采矿寻找黄金。它比简单的机器人要有效得多',
    'message me': '留言给我',
    'Methane is a gas found in abundance on Venus. It can be used to power your company much more effectively than solid fuel': '甲烷是在金星上大量发现的一种气体。它可以比固体燃料更有效地为你的公司提供动力',
    'Notifications (Not Autosave': '通知(不是自动保存',
    'Similarly to the above, you can go to my ': '类似于上面，你可以去我的',
    'You can find the game on any of these sites:': '你可以在以下任何一个网站上找到本游戏:',
    'You can find the game on any of these sites': '你可以在以下任何一个网站上找到本游戏',
    'With Auto Emc (unlocked with rebirth), when you can automate multiple, the order will be top to bottom (always Max)': '自动Emc(解锁与重生)，当你可以自动化多个，顺序将从上到下(总是最大)',
    'What does this do?': '这有什么用?',
    'Where else can I find the game?': '我还可以在哪里找到游戏?',
    'This robot is the coolest guy in the solar system': '这个机器人是太阳系里最酷的家伙',
    'This requires ': '这要求 ',
    'This special container condenses carbon dioxide gas into diamonds, creating gems at a faster rate than any drill': '这个特殊的容器将二氧化碳气体压缩成钻石，形成宝石的速度比任何钻子都要快',
    'This technology, unheard of previously, is now a reality, thanks to those in the Sol Scientific Center. The Sphere can provide much energy for millions of years, but at what cost?': '多亏了太阳科学中心的研究，这项以前闻所未闻的技术现在已成为现实。这个球体可以提供数百万年的能量，但代价是什么呢?',
    'This teleposes blocks of rock from far underground to the surface so that Uranium can be mined more easily': '这一技术能将地下深处的大块岩石远程传送到地表，从而更容易地开采铀',
    'This tool almost melts parts of beaches to get silicon at a larger scale': '这个工具几乎融化了海滩的一部分，以获得更大范围的硅',
    'This type of blowtorch instantly turns sand into Silicon, but only on a small scale. To make it, extraterrestrial resources are required': '这种喷灯能瞬间将沙子变成硅，但只是在小范围内。要做到这一点，需要外星资源',
    'This weapon of mass destruction has been re-labelled and now hovers above coast-lines, or what is now left of them': '这种大规模毁灭性武器已经重新贴上了标签，现在悬挂在海岸线上，或者是现在剩下的海岸线上',
    'Uranium is used for nuclear power generation because when it is split, it releases huge amounts of Energy. For this reason, it is prominent in many advanced machines and for propulsion technology as it is useful for inter-star-system travel. Unfortunately, it is hard to get and it requires a lot of resources to radiation-proof equipment': '铀用于核能发电，因为当它分裂时，会释放大量的能量。由于这个原因，它在许多先进的机器和推进技术中是突出的，因为它是有用的星际系统旅行。不幸的是，它很难获得，它需要很多资源的防辐射设备',
    'Tools Used': '使用的工具',
    'Dyson Swarms and Sphere': '戴森蜂群和球体',
    'EMC is a technology only dreamt about back on Earth. Here, it\'s a reality. You can turn energy and plasma into regular resources, or, with large amounts, you can turn it into rare ones, which you are unable to find and have to make to acquire': 'EMC是一项只有在地球上才能实现的技术。这就是现实。你可以将能量和等离子体转化为常规资源，也可以将大量的能量和等离子体转化为稀有资源，而这些资源是你无法获取的',
    'Energy-Mass Conversion': '能量-质量转换',
    'Exploring Jupiter gives you access to Hydrogen': '探索木星可以让你获得氢气',
    'Exploring Mars unlocks Titanium production, which allows you to harvest Silicon on Earth and to build Methane power plants': '探索火星开启了钛的生产，让你可以在地球上收集硅，并建造甲烷发电厂',
    'Exploring Saturn gives you access to Helium': '探索土星能让你获得氦',
    'Exploring the asteroid belt gives you access to Gold and Silver': '探索小行星带可以让你获得黄金和白银',
    'Exploring the Kuiper Belt gives you access to the hidden base': '探索柯伊伯带可以让你进入隐藏的基地',
    'Exploring the Moon will unlock the collection of Lunarite': '探索月球将解锁月岩采集',
    'Exploring the Sol Center gives you access to the hidden base': '探索索尔中心可以让你进入隐藏的基地',
    'Exploring the Wonder Station will gives you access to Wonders and allow you to continue your research and travel even further than before': '探索奇迹站将让你接近奇迹，让你继续你的研究，比以前走得更远',
    'Exploring Venus will unlock methane and methane based power': '探索金星将释放出甲烷和基于甲烷的能源',
    'Flying into Gas Giants\' atmospheres with a big bucket is the best plan we\'ve had yet!': '带着一个大水桶飞进气态巨行星的大气层是我们迄今为止最好的计划!',
    'For rebuilding the Stargate, you will be able to explore outer space, beyond your own solar system': '为了重建星际之门，你将能够探索外太空，超越你自己的太阳系',
    'Plasma being a state of extreme energy, it can be used as a storage of large amounts and provides the ability to use higher tier machines and transmutations': '等离子体是一种极端的能量状态，它可以被用作大量的存储，并提供使用更高层次的机器和嬗变的能力',
    'Plasma is the 4th state of matter and is used by Tier 4 machines and large space structures as an extreme power source for your company. At first you can hold 100,000 plasma at once, but you can unlock and purchase Plasma Storage Units to increase this number': '等离子体是物质的第四种状态，被第四层机器和大空间结构用作你公司的极端电源。一开始你可以一次储存10万个等离子体，但是你可以解锁并购买等离子体存储设备来增加这个数量',
    'Have you checked all of the tabs to see if there is anything new? Maybe the guide has something about it? If not, feel free to ask me either on reddit or post it as an issue on github if you think there is a problem with the game': '你检查过所有的标签了吗?也许引导说了些什么?如果没有，你可以在reddit上问我，或者在github上发布你认为游戏有问题的问题',
    'Gold is a metal found inside asteroids. It is used to build some Wonders and for complex machinery': '黄金是在小行星内部发现的一种金属。它被用来建造一些奇迹和复杂的机器',
    'Future Plans': '未来的计划',
    'Hydrogen Collector': '氢收集器',
    'Ice, although it can be collected on Earth, is not nearly as profitable as flying to Pluto and back with space craft full of the stuff. It is mainly used for super-cooling technology necessary for Tier 4 machines': '冰，虽然可以在地球上收集，但它的收益远不如带着装满冰的宇宙飞船飞回冥王星。它主要用于第4层机器所需的超冷却技术',
    'In a fusion reaction, Energy is released when two light atomic nuclei are fused together to form one heavier atom. This is the same reaction that occurs in stars and produces a lot of power': '在聚变反应中，两个轻原子核融合在一起形成一个较重的原子时释放能量。这是在恒星中发生的同样的反应，产生大量的能量',
    'In the center of the room, you see a smouldered antenna dish, lying on the floor. A plaque next to it says \'Original Comms Relay between my first two star systems\'. A loud voice booms again from the speakers at the far corners of the floor: \'This is one of my most prized memorabilia, reminding me of the first message I sent between star systems\'. I will be elated if you repair this for me, and in return, I will help you on your mission to colonise the stars': '在房间的中央，你看到一个被烟熏的天线盘，躺在地板上。旁边的一块匾上写着“我的前两个星系之间的原始通讯中继”。一个响亮的声音再次从地板远处角落的扬声器中传出:“这是我最珍贵的纪念品之一，让我想起了我在星系间传递的第一个信息。”如果你能帮我修好它，我会很高兴，作为回报，我会帮你完成殖民星球的任务',
    'In the corner of the floor, you see a faintly glowing, large canister, propped up against the walls. The announcing message plays after pressing a red button next to it: \'This was my first antimatter tank for the maiden voyage of "The Interstellar", on my first trip to another star system. For repairing it and bringing back the memories, I will teach you about your own antimatter production to fuel your dreams of escaping your small piece of the universe.': '在地板的角落里，你看到一个微微发光的大罐子，靠在墙上。按下旁边的一个红色按钮后，播放着宣布信息:“这是我第一次为《星际穿越》(The Interstellar)首次航行使用反物质罐，这是我第一次前往另一个星系。”为了修复它并带回记忆，我将教你如何制造反物质，为你逃离宇宙的梦想提供燃料。',
    'In the large asteroid belt extending beyond Pluto, you see a large purple structure with a huge glass dome on one of the asteroids. This seems worth checking out. There could be something interesting there': '在冥王星之外的小行星带，你可以看到一个巨大的紫色结构，在其中一个小行星上有一个巨大的玻璃圆顶。这似乎值得一查。这里可能有些有趣的东西',
    'Instead of going out and finding lava, it can be more convenient to make it yourself with heat and pressure': '与其出去寻找熔岩，还不如自己加热加压，这样更方便',
    'It will probably be self-explanatory, be explained in the description or in the wiki. If not, tell me and I will add it to the item, wiki or to the Frequently Asked Questions page': '它可能是不言自明的，可以在描述或wiki中进行解释。如果没有，告诉我，我会将其添加到条目、wiki或常见问题页面',
    'Outer Planet Machines': '外行星机器',
    'Oxidisation': '氧化作用',
    'Oxidisation Chambers make rocket fuel faster and more efficiently than chemical plants': '氧化室使火箭燃料比化学工厂更快更有效',
    'Oil Processing': '石油加工',
    'New Issue': '新问题',
    'Most of the images are from ': '大部分图片都来自于 ',
    'Hydrazine': '肼',
    'Hydrogen is extremely common on gas giants such as Jupiter and Saturn': '氢在像木星和土星这样的气态巨行星上非常常见',
    'However, I like the donation system because there is nothing forcing you to donate other than out of the goodness of people\'s hearts. If you like the game and want more content faster, I would be happy to put more time towards this game if I felt that it is paying off': '然而，我喜欢捐赠系统，因为没有什么强迫你捐赠，除了出于人们的善良的心。如果你喜欢这款游戏并且想要更快地获得更多内容，如果我觉得这款游戏值得我投入更多时间，我将非常乐意',
    'Notifications (Not Autosave)': '通知(不是自动保存)',
    'Now with a pyramid of energy at his disposal, the Overlord grants you some of his technology to produce electricity': '现在，有了金字塔能量的支配，领主会授予你一些他的技术来发电',
    'Unlock Oil': '解锁 石油',
    'Unlock Batteries': '解锁 电池',
    'Unlock Space Travel': '解锁 太空旅行',
    'Unlock EMC': '解锁 EMC',
    'Unlock Hydrazine': '解锁 肼',
    'Unlock Oil': '解锁 石油',
    'Unlock Basic Energy Production': '解锁 基本能源生产',
    'Unlock Destruction': '解锁 毁灭',
    'Unlock Resource Machines': '解锁 资源机器',
    'Unlock Plasma': '解锁 等离子体',
    'Unlock Plasma Tier': '解锁 等离子T',
    'Unlock Storage': '解锁 存储',
    'Unlock Solar Panels': '解锁 太阳能板',
    'Nuclear Power Stations': '核电站',
    'This huge tanker holds large amounts of Helium and transports it from Saturn to Earth through the vacuum of space': '这艘巨大的油轮装载着大量的氦，并通过真空空间将其从土星运送到地球',
    'This is a mining machine modified to have 5 drills on its face. This allows for a massive increase in resources gained per second': '这是一台采矿机，它的表面经过改造，有5个钻头。这允许每秒获得大量的资源',
    'This huge factory is as large as a planet, fusing together Uranium from common elements': '这个巨大的工厂像行星一样大，把普通元素中的铀熔合在一起',
    'This game has different amounts output by each machine. This can make balancing your resources hard, especially your Energy, Charcoal and Wood as they are consumed by other machines. As at tip, prioritise which resources you should build machines for first - in most cases Metal - and produce the 2 Energy required for a heavy drill. Don\'t upgrade everything to machines at once as you will end up with an Energy deficit (this is bad as the machines won\'t work without Energy). Build up your Charcoal to build engines or increase the number of solar panels to counter this': '这个游戏有不同数量的输出，每台机器。这可能会使您的资源平衡困难，特别是您的能源，木炭和木材，因为他们是由其他机器消耗。正如tip所言，你应该优先考虑哪些资源应该先用于制造机器——在大多数情况下是金属——并生产重型钻头所需的两种能源。不要一次把所有的东西都升级到机器上，因为你最终会出现能量不足(这很糟糕，因为机器没有能量就不能工作)。增加木炭来制造引擎，或者增加太阳能电池板的数量来应对这种情况',
    'This extracts lava from volcanoes automatically and quickly': '这能自动快速地从火山中提取熔岩',
    'Turn Meteorite Production ': '切换陨石生产 ',
    'Turn Plasmatic Pit ': '切换 等离子坑 ',
    'Turn Super-Heater ': '切换 超级加热器 ',
    'Transmuation has progressed to being able to turn thin air into gold!': '转化已经进步到能够把稀薄的空气变成金子!',
    'Autosave Notifications': '自动保存通知',
    'Balancing Resources & Energy': '资源与能源的平衡',
    'Beginner\'s Guide': '新手指南',
    'Basic Energy Production': '基本能源生产',
    'Bribe local workers to mine your Lunarite': '贿赂当地工人开采你的月岩',
    'Burn powerful methane from Venus to satisfy all your power needs': '从金星燃烧强大的甲烷，以满足你所有的电力需求',
    'Building a rocket will allow for exploration around the solar system and will allow you to gather resources in space': '建造一枚火箭将允许围绕太阳系进行探索，并将允许你在太空中收集资源',
    'Change Company Name': '更改公司名称',
    'Change how long the game waits before auto-saving again': '改变游戏在自动保存之前等待的时间',
    'Collect gas from deep sea vents on the ocean floor of Titan': '从泰坦海底的深海喷口收集气体',
    'Chronal Actuator': '定向致动器',
    'Coloured Destroy Buttons': '彩色化摧毁按钮',
    'Compress Rows in Sidebar to Decrease White Space': '压缩侧边栏中的行以减少空白',
    'Condense gases from the heart of Jupiter into liquid magma': '将木星中心的气体凝结成液态岩浆',
    'Construct an automated way of producing meteorite without you having to do anything': '建造一个自动化的方式生产陨石，你不需要做任何事',
    'Construct Ring': '构造环',
    'Construct Sphere': '构造球体',
    'Construct Swarm': '构造群',
    'About': '关于',
    'Activate Portal': '激活传送门',
    'Activate Meteorite Wonder': '激活陨石奇迹',
    'Activate Energetic Wonder': '激活能量奇迹',
    'Activate Precious Wonder': '激活珍贵奇迹',
    'Activate Technological Wonder': '激活技术奇迹',
    'Activating the Portal will allow you to go through it to get to the Third Floor of the Wonder Station, detached from the rest of the tetrahedral monolith': '激活入口可以让你通过它到达奇迹站的三楼，与四面体整体的其余部分分离',
    'Activating this wonder gives you the ability to construct 4th Tier resource gathering machines, which are better and more efficient than anything before it': '激活这个功能可以让您构建第4层资源收集机器，它比之前的任何机器都更好、更高效',
    'Activating this wonder will allow you to build Tier 3 Machines, a much more effective method of collecting resources': '激活这个奇迹将允许你建造第三层机器，一个更有效的收集资源的方法',
    'Activating this wonder will allow you to harness the power of Lava, a new method of Energy generation': '激活这个奇迹将允许你利用熔岩的力量，一种新的能量产生方法',
    'Activating this wonder will teach you about Uranium, how to get it and how to harness it. Learning about this rare element found deep within Earth will unlock nuclear power, a new way to create Energy': '激活这个奇迹将教会你铀的知识，如何得到它，如何利用它。了解地球深处发现的这种稀有元素将开启核能，这是一种创造能源的新方法',
    'After trading resources with the Sol Center, they will give you some of their research on plasma and how to get it': '在与索尔中心交换资源之后，他们会给你一些关于等离子体的研究以及如何获得它',
    'A melting pot of misery, pouring lava out from mined rock': '一个苦难的大熔炉，从开采的岩石中喷出岩浆',
    'A pulsating image depicts a huge pyramid, with sparks of lightning. What could the Overlord want now?': '一幅跳动的图像描绘了一个巨大的金字塔，上面有闪电的火花。领主现在想要什么?',
    'A green-tinted picture shows the inside of some computer system': '绿色的图片显示了一些计算机系统的内部',
    'A contained miniature version of the sun uses nuclear fusion to create massive amounts of helium': '一个微型的太阳利用核聚变产生大量的氦',
    'A blazing red portrait depicts a futuristic set of machines': '一幅鲜红的肖像描绘了一组未来主义的机器',
    'Game Saved': '游戏已保存',
    'Stargaze': '观星',
    'As you enter the revolving pyramids, floating through space, you feel a small tug on your spacecraft as it gravitates towards an opening doorway in the side of the lowest section. Exiting your spacecraft, you experience the artificial gravity and walk to the large hallway ahead. Adorning the walls are four huge paintings of monolithic structures in the corners of the room with descriptions underneath. At the far end of the room is a giant door, closed without any indication of being able to open. You feel that there is a higher being watching over you as you walk through the room': '当你进入旋转的金字塔，漂浮在空间中，你会感觉到你的飞船有一个小的引力，因为它向最低部分的一个开放的门口。走出飞船，你体验了人造重力，并走向前方的大走廊。墙壁上装饰着四幅巨大的单片结构的画，画在房间的角落里，下面有描述。房间的另一端是一扇巨大的门，已经关上，却没有任何迹象表明它能打开。当你走过房间的时候，你感觉有一个更高的人在看着你',
    'A huge problem with the theory of interstellar space travel is on the verge of being broken. Make it happen with this upgrade. This is a one time upgrade, increasing your exploration range by 5 Light Years': '星际旅行理论的一个巨大问题即将被打破。用这个升级实现它。这是一次升级，增加你的探索距离5光年',
    'Alternatively, you can post/comment about it in ': '或者，你也可以发表评论在',
    'An interdimoonsional bovine': '星际间的牛',
    'An obsidian-looking giant-sized frame stands out in the room, mounted on the far wall of the floor. It\'s plaque reads: \'This is the pathway to the third and final floor of my mystical Wonder Station. It takes many resources to activate it, but once completed, will grant you access to the Stargate Room: The only way you will find your way out of this pathetic solar system and explore the cosmos\'': '房间里有一个看上去像黑曜石的巨型框架，安装在地板远处的墙上。上面的铭牌上写着:“这是通往我的神秘神奇站的第三层也是最后一层的通道。”启动它需要很多资源，但一旦完成，你就可以进入星际之门的房间:这是你走出这个可怜的太阳系，探索宇宙的唯一方法。',
    'And you wondered why we have a hundred moons in the sky?': '你想知道为什么我们会有一百个月亮在天上?',
    'Antimatter': '反物质',
    'Asteroid Destroyer': '小行星驱逐舰',
    'Astronomical Breakthrough': '天文突破',
    'Bathing in Electrons. What could go wrong?': '沐浴在电子中。会出什么问题呢?',
    'Travel': '旅行',
    'To unlock research, you must purchase a metal miner, costing 10 Metal and 5 Wood. This is the first step to idle automation. The Research tab is where you can build laboratories to produce science for you, and also where you can discover and research new technologies to further help you through the game': '要解锁研究，你必须购买一个金属矿工，花费10金属和5木材。这是实现空闲自动化的第一步。在 研究 选项卡中，你可以建立实验室来为你研究科学，也可以发现和研究新技术来进一步帮助你完成游戏',
    'Titanium is a metal found mostly on Mars. It is used for building strong machines and methane power plants': '钛是一种主要在火星上发现的金属。它被用来建造强大的机器和甲烷发电厂',
    'Time And Relative Dimensions In Sand': '时间和沙的相对尺寸',
    'United': '联合',
    'Upgrade Resource Technology': '升级资源技术',
    'Upgrade Engine Technology': '升级发动机技术',
    'Upgrade Solar Technology': '升级太阳能技术',
    'Welcome to our home. Our race is dedicated to scientific progress and interacting with others. If you wish to trade with us, we can provide you blueprints for technology that few in the galaxy have ever seen': '欢迎来到我们的家。 我们的比赛致力于科学进步并与他人互动。 如果您希望与我们进行贸易，我们可以为您提供银河系中很少见到的技术蓝图',
    'Venus is the hottest planet in the solar system and the closest one to Earth. It is rich in greenhouse gases, contributing to its extreme heat. You can extract methane from Venus, which allows you to build up a new form of power generation': '金星是太阳系中最热的行星，也是离地球最近的行星。 它富含温室气体，导致极高的热量。 您可以从金星中提取甲烷，从而建立新的发电形式',
    'Well, it isn\'t called Space Company for nothing. The first thing needed to unlock inter-planetary exploration is to build a rocket. This is the first large goal that you should aim for as a target. To build a rocket, you need a lot of resources, which you most likely need to use advanced machines to get without taking an extremely long time. Secondly, to launch it requires 20 rocket fuel, which can be made in chemical plants. These require a large amount of Oil and Charcoal to produce - 20 of each per second per plant. Once you have 20 Rocket Fuel and have built a rocket, press the launch button to unlock exploration around the solar system and new technologies and ways to get resources': '好吧，这并不是没有名叫太空公司。 解锁行星际探索所需的第一件事是制造火箭。 这是您应该以目标为目标的第一个大目标。 要制造火箭，您需要大量资源，而您很可能需要使用高级机器来获得这些资源，而又不会花费很长时间。 其次，发射它需要20枚火箭燃料，可以在化工厂生产。 这些需要大量的油和木炭才能生产-每棵植物每秒要生产20片。 一旦您拥有20枚火箭燃料并制造了火箭，请按发射按钮以解锁围绕太阳系的探索以及新技术和获取资源的方法',
    'Well, this isn\'t a full-time project for me. This means that although I will try to work on it as much as I can, progress can be slow. However, I will endeavour to release updates as often as I can and fix any bugs as quickly as possible': '好吧，这对我来说不是一个全职项目。 这意味着，尽管我将尽我所能进行最大的努力，但是进度可能会很慢。 但是，我将努力尽可能地发布更新，并尽快修复所有错误。',
    'Resource Machines': '资源机器',
    'Reticulating Splines..': '网状样条函数. .',
    'Resource Efficiency': '资源效率',
    'Research new technologies to unlock more mechanics and advance through the game': '研究新技术来解锁更多机制并在游戏中前进',
    'The Energetic Wonder': '能量奇迹',
    'Storage Upgrades': '存储升级',
    'The Magmatic Dynamo is a method of producing power by using lava as a fuel. Because of the extreme temperature of lava, a lot of Energy can be produced at once': '岩浆发电机是一种利用岩浆作为燃料来产生能量的方法。由于熔岩的温度极高，一次可以产生大量的能量',
    'They produce ': '它们生产 ',
    'This collector travels around Jupiter seeking Hydrogen to store to bring back to Earth': '这个收集器在木星周围寻找氢储存并带回地球',
    'Science Efficiency': '科学效率',
    'Scientific (*10^n': '科学 (*10^n',
    'Scientific (E+n': '科学 (E+n',
    'Shield Plating': '屏蔽镀层',
    'Rocket Ship': '火箭飞船',
    'Rockets': '火箭',
    'Thank you to all Donators and my supporters on Patreon!': '感谢所有Patreon的捐赠者和我的支持者！',
    'The Communication Wonder': '通信奇迹',
    'Your fuel for interstellar travel is produced here. Unfortunately, you can only handle 100k Antimatter per Star System as it is incredibly volatile': '星际旅行的燃料就是在这里生产的。不幸的是，每个星系只能处理100k的反物质，因为反物质的挥发性非常大',
    'This quarry tears up the surface of the moon so much that it can be seen from Earth': '这个采石场把月球表面挖得很深，从地球上都能看到',
    'This powerful reactor can turn high-energy plasma into the most efficient fuel we can imagine': '这个强大的反应堆可以将高能等离子体转化为我们所能想象的最高效的燃料',
    'This powerful cannon orbits Neptune and can atomise the surface of asteroids, revealing the silver within': '它强大的加农炮绕着海王星旋转，能使小行星表面雾化，从而发现里面有银',
    'This plating combats the Sun\'s radiation, and can protect anyone inside from the frigid cold of space': '这种镀层可以对抗太阳的辐射，可以保护室内的任何人免受太空的寒冷',
    'This mighty drill is said to have been wielded by Titans themselves, many millennia ago': '据说，早在几千年前，泰坦们就已经使用过这种强大的钻头',
    'This machine is the reason we\'re losing our rainforests. At least we get lots of wood!': '这台机器是我们失去雨林的原因。至少我们有很多木材!',
    'This large, space drill, named after the World War One Howitzer built almost a millennia ago, is a silver seeking machine specially designed for mining asteroids': '它是一种大型太空钻探设备，以近千年前制造的“一战”榴弹炮命名，是一种专门为采矿小行星而设计的寻找银的机器',
    'This large ship orbits around the planet, focused on the Sahara Desert, tearing up sand from Earth and turning it into Silicon under intense heat': '这艘巨轮围绕地球运行，聚焦于撒哈拉沙漠，从地球上撕下沙子，在高温下将其转化为硅',
    'This large machine dives deep into the Earth to find large pools of Lunarite found near the core. This is originally where the metal on the Moon comes from': '这台大型机器潜入地球深处，寻找在地核附近发现的大量月球石。这是月球上金属最初的来源',
    'This is where you learn about other systems to travel to. ': '在这里，您可以了解可以旅行的其他系统。',
    'This is where you can see your rank and all of your achievements': '在这里，您可以查看自己的排名和所有成就',
    'This is where you can see your progress in a table with each aspect laid out for you to see': '在这里，您可以在表格中查看进度，并列出了各个方面供您查看',
    'This is where you can convert your energy and plasma into resources. ': '在这里您可以将能量和等离子体转化为资源。',
    'This is where you can construct your transport to the stars': '在这里您可以建造前往星空的交通工具',
    'This is where you can change how your game is saved': '在这里您可以更改游戏的保存方式',
    'This guide will get you from starting the game to activating your first wonder and will be helpful to grasp everything you need to do. You can refer to this guide at anytime while playing by clicking the Help/FAQ tab in the top right and selecting the Getting Started sub-tab': '本指南将帮助您从开始游戏到激活您的第一个奇迹，并有助于您掌握所需要做的一切。 您可以在播放时随时通过单击右上角的“帮助/常见问题”选项卡并选择“入门”子选项卡来参考本指南。',
    'This contraption converts Helium into Plasma through firing intensive energy bolts at the gas cloud': '通过在气体云上发射密集的能量螺栓将氦气转化为等离子体',
    'The Stargate Room': '星际之门厅',
    'The Technological Wonder': '技术奇迹',
    'Rebuild Rocket Wonder': '重建火箭奇迹',
    'Recycles used-up Uranium to provide the resources with a second use. This greatly increases the amount of Uranium you can use per second': '回收利用完的铀，为资源提供二次利用。这大大增加了你每秒可以使用的铀的量',
    'EQ Pegasi': 'EQ 飞马座',
    'EV Lacertae': 'EV 蝎虎座',
    'EZ Aquarii': 'EZ 水瓶座',
    'FI Virginis': 'FI 处女座',
    'Epsilon Indi': '印第安座ε',
    'Epsilon Eridani': '波江座',
    'CN Leonis': 'CN 狮子座',
    'AD Leonis': 'AD 狮子座',
    'DO Cephei': 'DO 仙王座',
    'DX Cancri': 'DX 巨蟹座',
    'Altair': '牛郎星',
    'AX Microscopii': 'AX 显微镜座',
    'Barnard\'s Star': '巴纳德星',
    'Alpha Centauri': '阿尔法半人马座',
    'Kapteyn\'s Star': '',
    'Keid': '九州殊口增七',
    'Procyon': '小犬座α',
    'QY Aurigae': 'QY 御夫座',
    'Sigma Draconis': '冰雪世界达克尼斯星球',
    'Sirius': '大犬座',
    'Tau Ceti': 'Tau 鲸鱼座',
    'YZ Ceti': 'YZ 鲸鱼座',
    'Teegarden\'s Star': '蒂加登星',
    'V1054 Ophiuchi': 'V1054 蛇夫座',
    'V1216 Sagittarii': 'V1216 射手座',
    'V1581 Cygni': 'V1581 天鹅座',
    'V577 Monocerotis': 'V577 麒麟座',
    'van Maanen\'s Star': '范马南星',
    '/ Second': '/ 秒',
    'Luyten\'s Star': '洛汀星',
    '"In the corner of the floor, you see a faintly glowing, large canister, propped up against the walls. The announcing message plays after pressing a red button next to it: \'This was my first antimatter tank for the maiden voyage of "The Interstellar", on my first trip to another star system. For repairing it and bringing back the memories, I will teach you about your own antimatter production to fuel your dreams of escaping your small piece of the universe.\'"': '在地板的角落里，你看到一个大罐子靠在墙上，微微发光。在按下旁边的一个红色按钮后，有信息被播放了出来:“这是我第一次到另一个星系旅行时，在星际号的处女航中使用的第一个反物质箱。”如果你们修复了它并带回我的记忆，我将教你们怎样生产你们自己的反物质来为你们逃离你们的宇宙小角落的梦想提供燃料。',
    'Lava, ': '岩浆, ',
    'Load': '加载',
    'Helium, ': '氦, ',
    'Gold, ': '黄金, ',
    'Hydrogen, ': '氢, ',
    'Ice, ': '冰, ',
    'Game': '游戏',
    'Gem': '宝石',
    'Gems per second': '宝石每秒',
    'Gems, ': '宝石, ',
    'Dyson Ring': '戴森环',
    'Does donating give me anything?': '捐赠能给我什么吗？',
    'Distance': '距离',
    'Defense': '防御',
    'Destroy': '摧毁',
    'Chance of Victory': '胜利的几率',
    'Buy': '购买',
    '"Having drained many stars of their energy, I want a structure built in honor of the energy I have taken from the galaxy with my mighty power. In return for building this, I will grant you ways to generate a form of power no man has been able to harness before."': '在消耗了许多恒星的能量之后，我想建造一个建筑来纪念我用我强大的力量从银河系中获取的能量。作为建造这个的回报，我将允许你产生一种以前没有人能够驾驭的力量',
    '"While I am rich beyond comparison, I still value adding precious resources to my collection. In return for your Gems, Silver, and Gold, I will teach you about something that lies inside your own planet, allowing you to find a rare resource and dangerous element previously unfound."': '虽然我是难以想象的富有，但我仍然喜欢对珍贵资源的收集。作为对你的宝石、白银和黄金的回报，我会教你发现一些在你自己的星球内部的东西，让你找到一种以前没有发现的稀有而危险的元素资源',
    '"With my technological superiority over anyone in the cosmos, I want a monument dedicated to the advanced computer systems I control. As a reward, I will teach you about computerized machines and give you the ability to make more advanced resource gatherers."': '鉴于在宇宙中没人比我技术更先进，我想要一座赞美我所控制的先进计算机系统的纪念碑。作为回报，我会教你使用计算机化的机器，让你有能力进行更先进的资源采集。',
    '"You have accomplished much so far, but now you face building a great structure to last generations. For my next monument, I will gift you with a new type of machine only seen in science-fiction. Meteorite machines use the energy installed in them to convert plasma into raw power useful in extracting resources."': '到目前为止，你们已经取得了很大的成就，但是现在你们面临的是为子孙后代建造一个伟大的建筑。对于我的下一个纪念碑，我将送给你一种只有在科幻小说中才能见到的新型机器。陨石机利用安装在其上的能量装置将等离子转化为用于提取资源的原始动力',
    '; you can ': '; 你可以 ',
    'Hard Reset': '硬复位',
    'Groombridge': '新郎桥',
    'Invade': '入侵',
    'Lab Discount': '实验室折扣',
    'More..': '更多..',
    'Help / FAQ': '帮助 / 问答',
    'Offline Gains': '离线收益',
    'Overlord Cult': '霸主崇拜',
    'Get': '获得',
    'General': '常规',
    'Attack!': '攻击!',
    'Automated EMC': '自动化EMC',
    'Battle Cruiser': '战列巡洋舰',
    'Battery Efficiency': '电池效率',
    'Close': '关闭',
    'Dark Matter': '暗物质',
    'Dark Matter Boost': '暗物质提升',
    'Current Rank': '当前排名',
    'Unlockables': '解锁',
    'Unlock the Space Scientific Satellite Station': '解锁空间科学卫星站',
    'Unlock the Planet Smasher building': '解锁行星粉碎机建筑',
    'Unlock the Nebulous Synthesizer building': '解锁星云合成器建筑',
    'Unlock the fifth tier of batteries for all your energy storage needs': '解锁第五层电池，满足您所有的储能需求',
    'Total Fleet Attributes': '舰队总属性',
    'Respec': '规格',
    'Right click to go back X': '右键单击返回 X',
    'Ring': '环',
    'Rocket Discount': '火箭折扣',
    'Save': '保存',
    'Resources': '资源',
    'Resource Production': '资源生产',
    'Research Efficiency': '研究效率',
    'Relationship': '关系',
    'Portal Room': '门户室',
    'Planets': '行星',
    'per second': '每秒',
    'Wonders': '奇迹',
    'Space Noob': '太空菜鸟',
    'Spaceship Pilot': '宇宙飞船驾驶员',
    'Speed': '速度',
    'Starting Storage': '开始存储',
    'Starting Labs': '开始实验',
    'Storage Discount': '仓储折扣',
    'Success Chance': '成功几率',
    'System Fleet Statistics': '系统舰队统计',
    'Threat Level: (': '威胁级别: (',
    'Get Rocket Ship': '获取火箭飞船',
    'Get Shield Plating': '获取屏蔽镀层',
    'Get Engine Unit': '获取引擎单元',
    'Get Astronomical Breakthrough': '获取天文突破',
    'Get Aerodynamic Sections': '获取空气动力学截面',
    'Get Interstellar Radar Scanner': '获取星际雷达扫描仪',
    'Toggle Antimatter ': '切换反物质 ',
    'To understand this supreme construct, you must request the aliens\' help. They require vast amounts of energy and plasma': '要了解这种最高的构造，您必须请求外星人的帮助。 它们需要大量的能量和等离子体',
    'Unlock the Electron Bath': '解锁电子浴',
    'Unlock T2 PSUs': '解锁T2电源模块',
    'Using Nano-technology, tiny universes can be created, filled with toxic gases from charcoal production and simply deleted. Cross-dimensional pollution at a completely new level!': '使用纳米技术，可以创建微小的宇宙，充满木炭生产中的有毒气体，然后将其删除。 跨维度的污染达到了全新的水平！',
    'Up on the second floor, you find a disarray of broken machines and scattered parts on the floor. You can reassemble what seems to be a rocket engine lying next to you. The booming voice of the Overlord comes over the speakers in the room: \'Greetings, friend. As you can see, this floor has largely fallen into disorder. If you fix it for me, you will be handsomely rewarded. Your first task is to repair the wonder to your right. It used to be a rocket engine, but I\'m not sure where the pieces are. You may need additional research to build this once more, but I\'m sure you will figure it out just fine.\'': '在第二层，您发现地板上散落着破碎的机器和零散的零件。 您可以重新组装似乎旁边的火箭发动机。 霸王的轰鸣声传遍了房间的扬声器：“问候，朋友。 如您所见，此地板已大体陷入混乱。 如果为我修复它，您将获得丰厚的回报。 您的首要任务是在您的右边修复奇迹。 它曾经是火箭发动机，但我不确定这些零件在哪里。 您可能需要其他研究才能再次构建此模型，但是我敢肯定，您会发现它很好。',
    'When you have made a mistake or want to change your upgrades, you can respec and refund every upgrade for dark matter. Unfortunately, this huge amount of power can only be unleashed a finite number of times. The Overlord graciously gives you 3 free chances at redemption, but the rest will have to be earned through rebirth (1 extra every 3 times).': '如果您犯了一个错误或想要更改升级，您可以重新指定并退还每次升级的暗物质。 不幸的是，这种巨大的力量只能释放有限的次数。 霸主慷慨地给您3次免费兑换的机会，但其余的必须通过重生获得（每3次额外赚取1次）。',
    'storage': '存储',
    'System Fleet Power/Defense Multiplier (Reputation': '系统舰队力量/防御乘数（声誉',
    'Tabs Unlocked': '标签已解锁',
    'Technologies Researched': '已研究技术',
    'The Overlord wishes for a cube made up of ': '领主的愿望是一个立方体由',
    'The Overlord, watching his newly built wonder, offers you the possibility for a new wave of machines that best any before them': '霸王看着他的新建奇迹，为您提供了新一轮最适合他们的机器的可能性。',
    'The planet that rotates differently from everyone else has winds up to 300 miles per hour (483kph). Its composition is much like that of the other gas giants, mainly composed of Hydrogen and Helium. Because of this, it is not worth exploring to get the same resources as in Saturn and Jupiter': '与其他行星旋转不同的行星每小时的风速高达300英里（483kph）。 其组成与其他主要由氢和氦组成的气体巨头的组成非常相似。 因此，获得与土星和木星相同的资源是不值得探索的',
    'Activated': '已激活',
    'Active Scouts': '活动侦察兵',
    "Metal, ": "金属, ",
    "Metal, Hydrogen": "金属, 氢气",
    "Metal, Meteorite": "金属, 陨石",
    "Metal, Titanium": "金属, 钛",
    "Methane, ": "甲烷, ",
    "Meterorite": "陨石",
    "Meteorite Tier": "陨石层级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    'The Capital Ship is a Defense-heavy ship, but can still pack a punch with it\'s large attack force. The main downside is the slow speed, dragging the fleet\'s manouverability down': '主力舰是一艘重型防御舰，但仍能以其强大的攻击力量进行重击。主要的缺点是速度太慢，拖慢了舰队的机动性',
    'The Battle Cruiser is a costly investment, but pays off with a balanced mix of power, defense and speed. It is a high-end ship, both in terms of attributes and cost': '战列巡洋舰是一项昂贵的投资，但要在力量，防御和速度之间取得平衡，才能获得回报。 从属性和成本两方面来看，这是一艘高端船',
    'The asteroid belt is a vast space with nearly 2 million asteroids. There you can harvest rare metals on Earth more easily, such as Gold and Silver': '小行星带是一个拥有近200万颗小行星的广阔空间。 在这里，您可以更轻松地在地球上收获稀有金属，例如金和银',
    'on reddit, put it in a comment on any post (or make a post) at ': '在reddit上，在以下位置发表帖子（或发表评论）',
    'Oil used to fuel more advanced machines that gather resources and also to produce more power than basic means. Unlocking Oil Processing allows you to extract it from the ground': '用来为更先进的机器提供燃料的油，这些机器会收集资源，并产生比基本方式更多的动力。 解锁油处理工艺可让您从地面提取油',
    'No. I didn\'t want to make this game pay-to-win and make people feel that they had to pay money to get further in the game because this makes it less appealing to those who don\'t want to donate': '不，我不想让这款游戏赢钱，让人觉得他们必须付费才能在游戏中取得更大的进步，因为这会使它对那些不想捐赠的人失去吸引力',
    'No-one knows what lies near and around pluto as it is so far away. On there surface, there is almost only ice, but maybe an exploration will teach us more about the unknown': '到目前为止，没人知道冥王星附近和周围有什么。 在那表面上，几乎只有冰，但是也许探索会教给我们更多关于未知的东西',
    'New Update!': '新内容！',
    'NB: You will lose machines gained with these ugprades, including all T5 machines. You will also divide your storage by 128 if you have the starting storage. (6400/50 = 128)': '注意：您将失去使用这些升级获得的机器，包括所有T5机器。 如果您有初始存储空间，则还将存储空间除以128。 （6400/50 = 128）',
    'NB: You will keep all upgrades purchased in your previous life  ': '注意：您将保留前世购买的所有升级产品',
    'NB: You only need 1 Rocket. You can reuse the same one by just using fuel': '注意：您只需要1枚火箭弹。 您可以只使用燃料就可以重复使用相同的燃料',
    'NB: You must activate the wonders after building them to receive their effects': '注意：您必须在建造奇迹之后激活奇迹才能获得其效果',
    'These combine antimatter with matter in a controlled reaction to create propulsion that will carry you to the stars': '它们在受控的反应中将反物质与物质结合起来，创造出将带你去星际的推进力',
    'These drills practically float!': '这些钻头实际上是漂浮的!',
    'These hold cows genetically moodified to produce methane constantly': '这些可以使转基因奶牛不断产生甲烷',
    'These large kilns are much more effective than previous methods of creating charcoal and use less wood to make the same amount as a furnace': '这些大型窑炉比以前的木炭生产方法更有效，并且使用更少的木材制成与窑炉相同的数量',
    'These mega-structures cannot possibly be built in one piece. They must be created from small sections and forged together around the sun': '这些巨型结构不可能一成不变。 它们必须由小部分制成，并在阳光下一起锻造',
    'These speed up the chemical reactions needed to make rocket fuel by using greenhouse gases such as methane': '这些通过使用诸如甲烷之类的温室气体来加速制造火箭燃料所需的化学反应。',
    'They use 520 Methane each second': '他们每秒使用520甲烷',
    'This private company has grown powerful over the galaxy and is inspired by profits, with allies to those who can support their aims. Upgrades offered focus on passive gains, with a large amount of automation': '这家私营公司在银河系方面已经发展壮大，并受到了利润的鼓舞，与能够支持其目标的人结盟。 升级提供了对被动收益的关注，并实现了大量自动化',
    'This research unlocks the second tier of Plasma production, the Plasmatic Pit': '这项研究开启了等离子生产的第二层，即等离子坑',
    'This will allow you to build storage upgrades to increase the maximum on the amount of resource you can have at once': '这将允许您构建存储升级，以增加一次可以拥有的最大资源量',
    'Time Played': '游戏时长',
    'Times rebirthed': '时代重生',
    'Timing': '定时',
    'Tier': '层',
    'You get Dark Matter for the floors of the Wonder Station that you complete. It is likely you will have achieved all of these in your first run before resetting. You get 4 Dark Matter for every floor completed, but 2 for the last floor (only one wonder)': '你完成了奇迹站的地板，你得到了暗物质。在重新设置之前的第一次运行中，您很可能已经实现了所有这些。每完成一层得到4个暗物质，但最后一层得到2个暗物质(只有一个奇迹)',
    'You will be able to produce power from steam engines using Charcoal made from wood in a furnace': '你可以用蒸汽机在炉子里用木头制成的木炭来产生动力',
    'Your Active Fleet Statistics': '你的活跃舰队统计',
    'Your Invasion Fleet': '您的入侵舰队',
    'Gain access to a fifth tier of machines to produce resources': '获得访问第五层机器以生产资源的权限',
    'Upgrade Charcoal Engines': '升级 木炭发动机',
    'Upgrade Resource Tech': '升级 资源技术',
    'Upgrade Solar Panels': '升级 太阳能板',
    'Unlock Meteorite Tier': '解锁 陨石T',
    'Unlock Meteorite': '解锁 陨石',
    'Unlock PSUs': '解锁 电源模块',
    'Unlock Oxidisation': '解锁 氧化作用',
    'Unlock Dyson Rings': '解锁 戴森环',
    'Unlock Dyson Swarms/Spheres': '解锁 戴森群/球',
    'Unlock': '解锁',
    'Battery Efficiency improves the storage capabilities of your batteries by 1% per upgrade': '电池效率提高你的电池的存储能力每次升级1%',
    'Costs ': '花费 ',
    'Dyson Rings produce huge amounts of energy by surrounding the sun in solar stations': '戴森环通过围绕太阳能站中的太阳产生大量能量',
    'Hydrazine is a compound created by Methane that increases the speed at which rocket fuel can be produced in a Hydrazine Catalyst Machine': '肼是甲烷产生的化合物，可提高在肼催化器中生产火箭燃料的速度',
    'Make your resource machines produce even more resources than before. This upgrade doubles the amount they produce for each unit of Energy': '使您的资源机器产生比以前更多的资源。 此次升级使每单位能源产生的产量翻倍',
    'Interstellar': '星际',
    'Science Efficiency increases the science production by 2% per purchase': '科学效率使每次采购的科学产出增加2%',
    'Solar Panels produce Energy without the need for fuel, but they do it slower than other forms of Energy production': '太阳能电池板不需要燃料就能产生能量，但它比其他形式的能源生产要慢',
    'Resource Machines produce more resources than simple methods but require a constant supply of power to work': '资源机器比简单的方法产生更多的资源，但需要持续的电力供应工作',
    'Resource Efficiency increases the income of resources by 1%/s per purchase': '资源效率使每次购买的资源收益增加1%/秒',
    'Researching this will allow you to increase your science production drastically': '研究这一点将使您大大提高科学生产能力',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    //    " ": "",
    ": ": ": ",
    "\n": "",
    "										": "",
    "								": "",
    "						": "",
    "		": "",
    "	": "",
    " ": " ",
    "Resources Present: ": "现有资源：",
    "XP = Star position:": "XP = 星星位置:",
    "The first painting depicts a large, shiny structure and the plaque reads": "第一幅画描绘了一个大型的，有光泽的结构，匾额写着",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    //    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "\n": "",
    "\n	": "",
    "\n											": "",
    "\n										": "",
    "\n									": "",
    "\n								": "",
    "\n							": "",
    "\n					": "",
    "\n				": "",
    ",": ",",
    ".": ".",
    ": Invasion": ": 入侵",
    ": Espionage": ": 间谍",
    ": Absorption": ": 吸收",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
    /^距离：(.+) \($/, //2.177e+6/s (+4.01+4/s tot
    /^每秒消耗 (.+)$/, //2.177e+6/s (+4.01+4/s tot
    /^每秒生产 (.+)$/, //2.177e+6/s (+4.01+4/s tot
    /^(.+): 间谍$/, //2.177e+6/s (+4.01+4/s tot
    /^(.+): 入侵$/, //2.177e+6/s (+4.01+4/s tot
    /^(.+): 吸收$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Uses (.+) Energy and (.+) Hydrogen per second$/, '每秒消耗 $1 能源 和 $2 氢气'],
    [/^Uses (.+) Energy and (.+) Helium per second$/, '每秒消耗 $1 能源 和 $2 氦气'],
    [/^Uses (.+) Energy and (.+) Helium and (.+) Hydrogen per second$/, '每秒消耗 $1 能源 和 $2 氦气 和 $3 氢气'],
    [/^Uses (.+) Energy per second$/, '每秒消耗 $1 能量'],
    [/^Uses (.+) Wood per second$/, '每秒消耗 $1 木头'],
    [/^Uses (.+) wood per second$/, '每秒消耗 $1 木头'],
    [/^They use (.+) Oil and (.+) Charcoal each second$/, '他们每秒使用 $1 石油和 $2 木炭'],
    [/^Produces (.+) Charcoal per second$/, '每秒生产 $1 木炭'],
    [/^Produces (.+) gem per second$/, '每秒生产 $1 宝石'],
    [/^Produces (.+) Gold per second$/, '每秒生产 $1 黄金'],
    [/^Produces (.+) Lunarite per second$/, '每秒生产 $1 月岩。'],
    [/^Produces (.+) Metal per second$/, '每秒生产 $1 金属'],
    [/^Produces (.+) methane per second$/, '每秒生产 $1 甲烷'],
    [/^Produces (.+) Oil per second$/, '每秒生产 $1 石油'],
    [/^Produces ([\d\.,]+) Plasma per second$/, '每秒生产 $1 等离子体'],
    [/^Produces (.+) Meteorite per second. Uses (.+) Plasma per second$/, '每秒生产 $1 陨石。每秒消耗 $2 等离子体'],
    [/^Produces (.+) silicon per second$/, '每秒生产 $1 硅'],
    [/^Produces (.+) Titanium per second$/, '每秒生产 $1 钛'],
    [/^Produces (.+) Uranium per second$/, '每秒生产 $1 铀'],
    [/^Produces (.+) wood per second$/, '每秒生产 $1 木头'],
    [/^Produces (.+) Helium per second$/, '每秒生产 $1 氦气'],
    [/^Produces (.+) Hydrogen per second$/, '每秒生产 $1 氢气'],
    [/^Produces (.+) Ice per second$/, '每秒生产 $1 冰'],
    [/^Produces (.+) silver per second$/, '每秒生产 $1 银'],
    [/^Produces (.+) Lava per second$/, '每秒生产 $1 岩浆'],
    [/^They produce (.+) Metal per second$/, '他们每秒生产 $1 金属。'],
    [/^They produce (.+) Rocket Fuel per second$/, '他们每秒生产 $1 火箭燃料。'],
    [/^They use (.+) Energy per second$/, '他们每秒消耗 $1 能源。'],
    [/^They use (.+) Methane per second$/, '他们每秒消耗 $1 甲烷。'],
    [/^They use (.+) Oil and (.+) Charcoal per second$/, '他们每秒消耗 $1 石油 和 $2 木炭。'],
    [/^Tier (.+) Batteries improve the amount of energy you can store at once$/, 'T$1 电池可提高您一次存储的能量'],
    [/^Distance: (.+) \($/, '距离：$1 \('],
    [/^T(.+) Batteries$/, 'T$1 电池'],
    [/^T(.+) PSUs$/, 'T$1 电源模块'],
    [/^Costs: (.+) Dark Matter$/, '成本: $1 暗物质'],
    [/^(.+) Antimatter$/, '$1 反物质'],
    [/^LP (.+)-(.+)$/, 'LP $1-$2'],
    [/^Luyten (.+)-(.+)$/, '洛汀 $1-$2'],
    [/^Gliese (.+)$/, '$1 冰'],
    [/^Autosaving in (.+) seconds$/, '将于 $1 秒后自动保存'],
    [/^(.+) Ice$/, '$1 冰'],
    [/^(.+) Seconds$/, ' $1 秒'],
    [/^(.+) Minutes$/, ' $1 分钟'],
    [/^Tier (.+) Science$/, 'T$1 科学'],
    [/^You've been offline for (.+)$/, '您已经离线了 $1'],
    [/^Unlock (.+) Batteries$/, ' 解锁 $1 电池'],
    [/^Unlock Tier (.+) Science$/, ' 解锁 T$1 科学'],
    [/^Each Power Station produces (.+) Energy and uses (.+) uranium per second$/, '每个电站产生 $1 能量，每秒使用 $2 铀'],
    [/^Each Power Station produces (.+) Energy and uses (.+) lava per second$/, '每个电站产生 $1 能量，每秒使用 $2 岩浆'],
    [/^Each Power Station produces (.+) Energy and uses (.+) methane per second$/, '每个电站产生 $1 能量，每秒使用 $2 甲烷'],
    [/^Each Power Station produces (.+) Energy and uses (.+) Hydrogen and (.+) Helium per second$/, '每个电站产生 $1 能量，每秒使用 $2 氢气 和 $3 氦气'],
    [/^Tier (.+) Batteries increase your energy storage by (.+) per battery built$/, 'T$1 电池增加你的能量存储,每组电池增加 $2'],
    [/^Each one produces (.+) science per second$/, '每一个每秒产生 $1 科学'],

]);
